# Generated by Django 3.2 on 2021-04-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(max_length=50)),
                ('page_name', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('custom_name', models.CharField(max_length=50)),
                ('custom_note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date_of_creation', models.DateField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark_manager_app.user')),
            ],
            options={
                'unique_together': {('name', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('time_of_creation', models.DateTimeField(max_length=100)),
                ('reminder_time', models.DateTimeField(max_length=100)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark_manager_app.bookmark')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark_manager_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_creation', models.DateField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark_manager_app.user')),
            ],
            options={
                'unique_together': {('name', 'creator')},
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark_manager_app.user'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark_manager_app.group'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='list_of_tags',
            field=models.ManyToManyField(blank=True, to='bookmark_manager_app.Tag'),
        ),
    ]
