# Generated by Django 3.2 on 2021-04-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_manager_app', '0002_rename_user_actor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='User',
        ),
    ]
