# Generated by Django 3.2 on 2021-04-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_manager_app', '0003_rename_actor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='page_name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
