from django.utils import timezone
from django.http import HttpResponse
import datetime
from .. import models

def dummydata(request):
    user1 = models.User(name="user1")
    user1.save()
    user2 = models.User(name="user2")
    user2.save()

    tag11 = models.Tag(name="tag11", creator=user1, date_of_creation=timezone.now())
    tag11.save()
    tag12 = models.Tag(name="tag12", creator=user1, date_of_creation=timezone.now())
    tag12.save()
    tag21 = models.Tag(name="tag21", creator=user2, date_of_creation=timezone.now())
    tag21.save()
    tag22 = models.Tag(name="tag22", creator=user2, date_of_creation=timezone.now())
    tag22.save()

    group11 = models.Group(name="group11", creator=user1, date_of_creation=timezone.now())
    group11.save()
    group12 = models.Group(name="group12", creator=user1, date_of_creation=timezone.now())
    group12.save()
    group21 = models.Group(name="group21", creator=user2, date_of_creation=timezone.now())
    group21.save()
    group22 = models.Group(name="group22", creator=user2, date_of_creation=timezone.now())
    group22.save()

    bkmark11 = models.Bookmark(url="www.bkmark11.com", custom_name="bkmark11", creator=user1, group=group11, date_of_creation=timezone.now())
    bkmark11.save()
    bkmark12 = models.Bookmark(url="www.bkmark12.com", custom_name="bkmark12", creator=user1, group=group11, date_of_creation=timezone.now())
    bkmark12.save()
    bkmark13 = models.Bookmark(url="www.bkmark13.com", custom_name="bkmark13", creator=user1, group=group12, date_of_creation=timezone.now())
    bkmark13.save()
    bkmark14 = models.Bookmark(url="www.bkmark14.com", custom_name="bkmark14", creator=user1, group=group12, date_of_creation=timezone.now())
    bkmark14.save()
    bkmark21 = models.Bookmark(url="www.bkmark21.com", custom_name="bkmark21", creator=user2, group=group21, date_of_creation=timezone.now())
    bkmark21.save()
    bkmark22 = models.Bookmark(url="www.bkmark22.com", custom_name="bkmark22", creator=user2, group=group21, date_of_creation=timezone.now())
    bkmark22.save()
    bkmark23 = models.Bookmark(url="www.bkmark23.com", custom_name="bkmark23", creator=user2, group=group22, date_of_creation=timezone.now())
    bkmark23.save()
    bkmark24 = models.Bookmark(url="www.bkmark24.com", custom_name="bkmark24", creator=user2, group=group22, date_of_creation=timezone.now())
    bkmark24.save()

    bkmark11.list_of_tags.add(tag11)
    bkmark11.save()
    bkmark12.list_of_tags.add(tag11, tag12)
    bkmark12.save()
    bkmark13.list_of_tags.add(tag12)
    bkmark13.save()
    bkmark14.list_of_tags.add(tag11, tag12)
    bkmark14.save()
    bkmark21.list_of_tags.add(tag21)
    bkmark21.save()
    bkmark22.list_of_tags.add(tag21, tag22)
    bkmark22.save()
    bkmark23.list_of_tags.add(tag22)
    bkmark23.save()
    bkmark24.list_of_tags.add(tag21, tag22)
    bkmark24.save()

    reminder1 = models.Reminder(name="reminder1", creator=user1, bookmark=bkmark14, reminder_time=timezone.now()+datetime.timedelta(days=10), time_of_creation=timezone.now())
    reminder1.save()
    reminder2 = models.Reminder(name="reminder2", creator=user2, bookmark=bkmark24, reminder_time=timezone.now()+datetime.timedelta(days=20), time_of_creation=timezone.now())
    reminder2.save()

    return HttpResponse("Dummy Data Initialized")